// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use crdt_store::{CrdtDb, MemoryStore, StateStore};

/// Create a [`CrdtDb`] with all generated migrations registered.
///
/// The database is configured for schema version 2 (the latest
/// version defined in the schema).
pub fn create_db<S: StateStore>(store: S) -> CrdtDb<S> {
    CrdtDb::builder(store, 2)
        .register_migration(super::task_migrations::register_migrate_task_v1_to_v2())
        .build()
}

/// Create a [`CrdtDb`] with [`MemoryStore`] for testing.
pub fn create_memory_db() -> CrdtDb<MemoryStore> {
    create_db(MemoryStore::new())
}
