// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use super::super::models::{TaskV1, TaskV2};
use crdt_migrate::migration;

/// Auto-generated migration: Task v1 -> v2
///
/// Added fields: priority (default: None), tags (default: Vec::new()), project_id (default: String::new())
#[migration(from = 1, to = 2)]
pub fn migrate_task_v1_to_v2(old: TaskV1) -> TaskV2 {
    TaskV2 {
        title: old.title,
        done: old.done,
        priority: None,
        tags: Vec::new(),
        project_id: String::new(),
    }
}
