// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use crdt_kit::prelude::*;

use super::super::models::Project;

/// Delta state for incremental sync of Project entities.
///
/// Only includes fields backed by `DeltaCrdt`-capable types.
/// Fields using state-based-only CRDTs (e.g., LWWRegister) are
/// synced via full-state merge instead.
#[derive(Debug, Clone)]
pub struct ProjectDelta {
    /// Delta for the `members` field.
    pub members: Option<ORSetDelta<String>>,
}

/// Compute the delta that `local` needs to catch up with `remote`.
///
/// Returns what `remote` has that `local` doesn't.
pub fn compute_project_delta(local: &Project, remote: &Project) -> ProjectDelta {
    ProjectDelta {
        members: Some(remote.members.delta(&local.members)),
    }
}

/// Apply a delta to a Project entity.
pub fn apply_project_delta(entity: &mut Project, delta: &ProjectDelta) {
    if let Some(d) = &delta.members {
        entity.members.apply_delta(d);
    }
}

/// Full-state merge for Project entities.
///
/// Merges all CRDT fields using the `Crdt::merge` trait method.
pub fn merge_project(local: &mut Project, remote: &Project) {
    local.name.merge(&remote.name);
    local.members.merge(&remote.members);
}
