// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

pub mod events;
pub mod migrations;
pub mod models;
pub mod repositories;
pub mod store;
pub mod sync;

pub use events::*;
pub use migrations::{create_db, create_memory_db};
pub use models::*;
pub use repositories::traits::*;
pub use store::*;
pub use sync::*;

// Entities defined in this persistence layer:
//   Project (table: "projects", latest version: v1)
//   Task (table: "tasks", latest version: v2)
