// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use crdt_store::{CrdtDb, MemoryStore, StateStore};

use super::migrations::create_db;
use super::repositories::project_repo::ProjectRepositoryAccess;
use super::repositories::task_repo::TaskRepositoryAccess;

/// Unified persistence layer providing repository access for all entities.
///
/// Owns a single `CrdtDb<S>` and provides scoped, typed access
/// to each entity's repository through borrow-checked accessor methods.
///
/// # Example
///
/// ```ignore
/// let mut persistence = create_memory_persistence();
/// let mut repo = persistence.projects();
/// repo.save("id-1", &entity)?;
/// ```
pub struct Persistence<S: StateStore> {
    db: CrdtDb<S>,
}

impl<S: StateStore> Persistence<S> {
    /// Create a new persistence layer with the given store.
    ///
    /// All migrations are automatically registered.
    pub fn new(store: S) -> Self {
        Persistence {
            db: create_db(store),
        }
    }

    /// Access the Project repository.
    pub fn projects(&mut self) -> ProjectRepositoryAccess<'_, S> {
        ProjectRepositoryAccess::new(&mut self.db)
    }

    /// Access the Task repository.
    pub fn tasks(&mut self) -> TaskRepositoryAccess<'_, S> {
        TaskRepositoryAccess::new(&mut self.db)
    }

    /// Access the underlying `CrdtDb` (read-only).
    pub fn db(&self) -> &CrdtDb<S> {
        &self.db
    }

    /// Access the underlying `CrdtDb` (mutable).
    pub fn db_mut(&mut self) -> &mut CrdtDb<S> {
        &mut self.db
    }
}

/// Create a persistence layer backed by an in-memory store.
///
/// Useful for testing and prototyping.
pub fn create_memory_persistence() -> Persistence<MemoryStore> {
    Persistence::new(MemoryStore::new())
}
