// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use crdt_kit::prelude::*;
use crdt_migrate::crdt_schema;
use serde::{Deserialize, Serialize};

/// Project entity -- version 1 (current)
#[crdt_schema(version = 1, table = "projects")]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProjectV1 {
    pub name: LWWRegister<String>,
    pub members: ORSet<String>,
}

/// Type alias for the current version.
pub type Project = ProjectV1;
