// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use crdt_migrate::crdt_schema;
use serde::{Deserialize, Serialize};

/// Task entity -- version 1
#[crdt_schema(version = 1, table = "tasks")]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TaskV1 {
    pub title: String,
    pub done: bool,
}

/// Task entity -- version 2 (current)
#[crdt_schema(version = 2, table = "tasks")]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TaskV2 {
    pub title: String,
    pub done: bool,
    pub priority: Option<u8>,
    pub tags: Vec<String>,
    pub project_id: String,
}

/// Type alias for the current version.
pub type Task = TaskV2;
