// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use serde::{Deserialize, Serialize};

/// Policy for determining when to create entity snapshots.
///
/// When event count reaches the threshold, a snapshot should be
/// taken to compact the event log and speed up entity reconstruction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SnapshotPolicy {
    /// Number of events before a snapshot is recommended.
    pub event_threshold: u64,
}

impl SnapshotPolicy {
    /// Check whether a snapshot should be created based on the event count.
    pub fn should_snapshot(&self, event_count: u64) -> bool {
        event_count >= self.event_threshold
    }
}

/// Default snapshot policy (threshold = 100).
pub const DEFAULT_POLICY: SnapshotPolicy = SnapshotPolicy {
    event_threshold: 100,
};
