// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use serde::{Deserialize, Serialize};

/// Events representing state changes for Project entities.
///
/// Used for event sourcing — each event captures a logical mutation
/// independent of the underlying CRDT representation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ProjectEvent {
    /// The entity was created with this initial state.
    Created(ProjectSnapshot),
    /// A field was updated.
    FieldUpdated(ProjectFieldUpdate),
    /// The entity was deleted.
    Deleted,
}

/// Complete snapshot of a Project entity's logical state.
///
/// Field types represent logical values (not CRDT wrappers).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProjectSnapshot {
    pub name: String,
    pub members: Vec<String>,
}

/// Individual field updates for Project entities.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ProjectFieldUpdate {
    /// Update to the `name` field.
    Name(String),
    /// Update to the `members` field.
    Members(Vec<String>),
}
