// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use serde::{Deserialize, Serialize};

/// Events representing state changes for Task entities.
///
/// Used for event sourcing — each event captures a logical mutation
/// independent of the underlying CRDT representation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum TaskEvent {
    /// The entity was created with this initial state.
    Created(TaskSnapshot),
    /// A field was updated.
    FieldUpdated(TaskFieldUpdate),
    /// The entity was deleted.
    Deleted,
}

/// Complete snapshot of a Task entity's logical state.
///
/// Field types represent logical values (not CRDT wrappers).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TaskSnapshot {
    pub title: String,
    pub done: bool,
    pub priority: Option<u8>,
    pub tags: Vec<String>,
    pub project_id: String,
}

/// Individual field updates for Task entities.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum TaskFieldUpdate {
    /// Update to the `title` field.
    Title(String),
    /// Update to the `done` field.
    Done(bool),
    /// Update to the `priority` field.
    Priority(Option<u8>),
    /// Update to the `tags` field.
    Tags(Vec<String>),
    /// Update to the `project_id` field.
    ProjectId(String),
}
