// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use crdt_store::{CrdtDb, DbError, StateStore};

use super::super::models::Project;
use super::traits::ProjectRepository;

/// Repository adapter for Project entities backed by `CrdtDb<S>`.
///
/// This is the "adapter" in hexagonal architecture. It implements
/// `ProjectRepository` using the CRDT-aware versioned store.
pub struct ProjectRepositoryAccess<'a, S: StateStore> {
    db: &'a mut CrdtDb<S>,
}

impl<'a, S: StateStore> ProjectRepositoryAccess<'a, S> {
    /// Create a new repository accessor with a mutable reference to the database.
    pub fn new(db: &'a mut CrdtDb<S>) -> Self {
        Self { db }
    }
}

impl<S: StateStore> ProjectRepository for ProjectRepositoryAccess<'_, S> {
    type Error = DbError<S::Error>;

    fn get(&mut self, id: &str) -> Result<Option<Project>, Self::Error> {
        self.db.load_ns("projects", id)
    }

    fn save(&mut self, id: &str, entity: &Project) -> Result<(), Self::Error> {
        self.db.save_ns("projects", id, entity)
    }

    fn delete(&mut self, id: &str) -> Result<(), Self::Error> {
        self.db.delete_ns("projects", id)
    }

    fn list(&mut self) -> Result<Vec<(String, Project)>, Self::Error> {
        let keys = self.db.list_keys_ns("projects")?;
        let mut result = Vec::new();
        for key in keys {
            if let Some(entity) = self.db.load_ns("projects", &key)? {
                result.push((key, entity));
            }
        }
        Ok(result)
    }

    fn exists(&self, id: &str) -> Result<bool, Self::Error> {
        self.db.exists_ns("projects", id)
    }
}
