// ============================================================================
// AUTO-GENERATED by crdt-codegen -- DO NOT EDIT
//
// This file was generated from a crdt-schema.toml definition.
// Any manual changes will be overwritten on the next `crdt generate` run.
//
// To modify this code, edit the schema file and re-run:
//   crdt generate --schema crdt-schema.toml
// ============================================================================

#![allow(dead_code, unused_imports)]

use std::fmt;

use super::super::models::{Project, Task};

/// Repository trait for Project entities (port in hexagonal architecture).
///
/// Implement this trait to provide persistence for Project entities.
/// The default adapter uses `CrdtDb<S>` (see `ProjectRepositoryAccess`).
pub trait ProjectRepository {
    /// Error type returned by repository operations.
    type Error: fmt::Debug + fmt::Display;

    /// Load a Project by its identifier.
    fn get(&mut self, id: &str) -> Result<Option<Project>, Self::Error>;

    /// Persist a Project with the given identifier.
    fn save(&mut self, id: &str, entity: &Project) -> Result<(), Self::Error>;

    /// Delete a Project by its identifier.
    fn delete(&mut self, id: &str) -> Result<(), Self::Error>;

    /// List all Project entities as `(id, entity)` pairs.
    fn list(&mut self) -> Result<Vec<(String, Project)>, Self::Error>;

    /// Check whether a Project with the given identifier exists.
    fn exists(&self, id: &str) -> Result<bool, Self::Error>;
}

/// Repository trait for Task entities (port in hexagonal architecture).
///
/// Implement this trait to provide persistence for Task entities.
/// The default adapter uses `CrdtDb<S>` (see `TaskRepositoryAccess`).
pub trait TaskRepository {
    /// Error type returned by repository operations.
    type Error: fmt::Debug + fmt::Display;

    /// Load a Task by its identifier.
    fn get(&mut self, id: &str) -> Result<Option<Task>, Self::Error>;

    /// Persist a Task with the given identifier.
    fn save(&mut self, id: &str, entity: &Task) -> Result<(), Self::Error>;

    /// Delete a Task by its identifier.
    fn delete(&mut self, id: &str) -> Result<(), Self::Error>;

    /// List all Task entities as `(id, entity)` pairs.
    fn list(&mut self) -> Result<Vec<(String, Task)>, Self::Error>;

    /// Check whether a Task with the given identifier exists.
    fn exists(&self, id: &str) -> Result<bool, Self::Error>;

    /// Find all Task entities related to a Project by `project_id`.
    fn find_by_project_id(&mut self, val: &str) -> Result<Vec<(String, Task)>, Self::Error>;
}
